version: '3.7'
services:
  discovery-server:
    image: discovery-server
    container_name: discovery-server
    ports:
      - 8761:8761
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - my-network
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    depends_on:
      - discovery-server
    ports:
      - 1234:1234
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge
    external: true
