version: '3.7'
services:
  discovery-server:
    container_name: discovery-server
    image: ${LOCATION}discovery-server${VERSION}
    ports:
      - 8761:8761
    volumes:
      - ${LOG_DIR}/discovery-server.log:/home/app/discovery-server/logs/discovery-server.log
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - school-house

  api-gateway:
    container_name: api-gateway
    image: ${LOCATION}api-gateway${VERSION}
    depends_on:
      - discovery-server
    ports:
      - 1234:1234
    volumes:
      - ${LOG_DIR}/api-gateway.log:/home/app/api-gateway/logs/api-gateway.log
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - school-house

networks:
  school-house:
    name: school-house
    driver: bridge
    external: true
