version: '3.7'
services:
  manage-ops:
    container_name: manage-ops
    image: ${LOCATION}manage-ops${VERSION}
    volumes:
      - ${LOG_DIR}:/home/app/manage-ops/logs
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - school-house
  syllabus-hub:
    container_name: syllabus-hub
    image: ${LOCATION}syllabus-hub${VERSION}
    volumes:
      - ${LOG_DIR}:/home/app/syllabus-hub/logs
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - school-house
  payments:
    container_name: payments
    image: ${LOCATION}payments${VERSION}
    volumes:
      - ${LOG_DIR}:/home/app/payments/logs
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - school-house

networks:
  school-house:
    driver: bridge
    external: true
