version: '3.7'
services:
  manage-ops:
    container_name: management-ops
    image: ${LOCATION}manage-ops${VERSION}
    volumes:
      - ${LOG_DIR}/manage-ops:/home/app/manage-ops/logs
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - school-house
  syllabus-hub:
    container_name: syllabus-hub
    image: ${LOCATION}syllabus-hub${VERSION}
    depends_on:
      - manage-ops
    volumes:
      - ${LOG_DIR}/syllabus-hub:/home/app/syllabus-hub/logs
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - school-house
  payments:
    container_name: payments
    image: ${LOCATION}payments${VERSION}
    depends_on:
      - manage-ops
    volumes:
      - ${LOG_DIR}/payments:/home/app/payments/logs
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - school-house

networks:
  school-house:
    external: true
    driver: bridge
    name: school-house
