server:
  port: 1234

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: management-ops
          uri: lb://management-ops
          predicates:
            - Path=/console/**,/dashboard/**,/app/dashboard/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@keyResolver}"
        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka-web**,/eureka/**
  redis:
    host: redis
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
