package com.myschool.constants;

public enum Privilege {
    ADMIN,
    STUDENT_ONBOARDING,
    COURSE_ONBOARDING,
    INSTRUCTOR_ONBOARDING,
    STAFF_ONBOARDING,
    SUBBRANCH_ONBOARDING,
    STUDENT_ATTENDANCE,
    INSTRUCTORS_ATTENDANCE,
    STAFF_ATTENDANCE,
    RECORD_FESS,
    PROCESS_SALARY
}
