pipeline {
    options {
        timestamps()
    }
    parameters {
        string(name: 'IMAGE_VERSION', defaultValue: 'latest', description: 'docker image default version')
    }
    agent any
    environment {
        ECR_REPO = '728976844027.dkr.ecr.ap-south-1.amazonaws.com'
    }
    stages {
        stage("Build") {
            steps {
                echo "Building application with mvn"
                sh 'mvn clean -Dmaven.test.skip=true install'
            }
        }
        stage("Test") {
            steps {
                echo 'Running Junit test cases'
                sh 'mvn test'
            }
        }
        stage("SonarQube Analysis") {
            steps {
                echo 'TODO'
            }
        }
        stage("Containerize") {
            steps {
                echo "$ECR_REPO and $IMAGE_VERSION"
                sh'''
                aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO
                docker build -t my-school .
                docker tag my-school:latest $ECR_REPO/my-school:$IMAGE_VERSION
                docker push $ECR_REPO/my-school:$IMAGE_VERSION
                '''
            }
        }
    }
    post {
        always {
            echo 'Process completed'
        }
        failure {
            echo 'Failure. Need to send email notification'
        }
        success {
            echo 'Success. Need to send push notification'
        }
    }
}