pipeline {
    options {
        timestamps()
    }
    parameters {
        string(name: 'IMAGE_VERSION', defaultValue: 'latest', description: 'docker image default version')
        choice(name: 'CONTAINERIZE', choices: ['Yes', 'No'], description: 'create docker container and push it to ecr')
        string(name: 'AWS_INSTANCE', description: 'aws instance Where container should be deployed')
    }
    agent any
    environment {
        ECR_REPO = '728976844027.dkr.ecr.ap-south-1.amazonaws.com'
        PRIVATE_AUTH_KEY = '/usr/auth/instance.pem'
    }
    stages {
        stage("Build") {
            steps {
                echo "Building application with mvn"
                sh 'mvn clean -Dmaven.test.skip=true install'
                echo "Build complete"
            }
        }
        stage("Test") {
            steps {
                echo 'Running Junit test cases'
                sh 'mvn test'
            }
        }
        stage("SonarQube Analysis") {
            steps {
                echo 'TODO: manually make sure SonarLint Intellij plugin is not showing any issues'
            }
        }
        stage("Containerize") {
            steps {
                echo "$ECR_REPO and $IMAGE_VERSION"
                sh'''
                aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO
                ./docker-build.sh $IMAGE_VERSION
                docker push $ECR_REPO/api-gateway:$IMAGE_VERSION
                docker push $ECR_REPO/discovery-server:$IMAGE_VERSION
                docker push $ECR_REPO/manage-ops:$IMAGE_VERSION
                docker push $ECR_REPO/payments:$IMAGE_VERSION
                docker push $ECR_REPO/syllabus-hub:$IMAGE_VERSION
                '''
            }
        }
    }
    post {
        always {
            echo 'Process completed'
        }
        failure {
            echo 'Failure. Need to send email notification'
        }
        success {
            echo 'Success. Need to send push notification'
        }
    }
}