server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
  dashboard:
    path: /eureka

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,info,health

logging:
  level:
    com:
      netflix:
        eureka: debug