server:
  port: 8761

spring:
  application:
    name: discovery-server

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,info,health

logging:
  level:
    com:
      netflix:
        eureka: debug