version: '3'
services:
  d-postgres:
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: my_school
  d-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 1234
