server:
  port: 0

spring:
  application:
    name: management-ops
  datasource:
    url: jdbc:postgresql://my-school.cqkytc8dhq8x.ap-south-1.rds.amazonaws.com:5432/my_school
    username: root
    password: root1234
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
    cleanDisabled: false
  kafka:
    bootstrap-servers: broker:29092
    producer:
      group-id: instituteEventId
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    com:
      myschool: INFO

eureka:
  client:
    service-url:
        defaultZone: http://discovery-server:8761/eureka
    registryFetchIntervalSeconds: 60

management:
  health:
    circuitbreakers:
      enabled: true
